### PR TITLE
health_probes: Handling service and Updating tests in appgw_tests

### PR DESCRIPTION
**Pull request by akshaysngupta**
1) When service is removed by the user, It makes no sense to make a probe object. We will just reference the default probe.
2) Modified appgw_test to do the upper level testing for health probe.

### CODE REVIEW

**Comment by bkarakashev** [comment]
hey, how can I define a custom path for the health prop?
I think the default is to use the path that is defined for the deployment... Can I overwrite that for example if my app is accessible on path /my-app can I have the health prop to be on path /health instead? If yes how? :) thanks

**Comment by akshaysngupta** [comment]
@bkarakashev You can specify `path: /health` in `readinessProbe` with `httpGet` for the Pod associated with the exposed service.
Refer: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

Also, feel free to try and report issues in the release candidate: 4b6a91a719ca19031f58765d9ff1d547a0fe58e2 carrying the health probe feature.
We will try to push a release out early next week.

**Comment by bkarakashev** [comment]
Hey, @akshaysngupta where do I need to set those settings for the custom health prope what will be the syntax?
This is how my app yaml file looks like:
Thanks.

`
apiVersion: v1
kind: Namespace
metadata:
  name: #{NAMESPACE}#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{DEPLOYMENT_NAME}#
  namespace: #{NAMESPACE}#
  labels:
    app: #{APP_NAME}#
    tier: #{TIER_NAME}#
spec:
  replicas: #{REPLICA_COUNT}#
  selector:
    matchLabels:
      app: #{APP_NAME}#
      tier: #{TIER_NAME}#
  template:
    metadata:
      labels:
        app: #{APP_NAME}#
        tier: #{TIER_NAME}#
    spec:
      containers:
      - name: #{APP_NAME}#
        image: #{ACR_IMAGE}#
        imagePullPolicy: Always
        env:
        - name: APP_NAME
          value: "#{APP_ENV}#"
        ports:
        - containerPort: #{CONTAINER_PORT}#
---
apiVersion: v1
kind: Service
metadata:
  name: #{SERVICE_NAME}#
  namespace: #{NAMESPACE}#
  labels:
    app: #{APP_NAME}#
    tier: #{TIER_NAME}#
spec:
  ports:
  - port: #{PORT}#
    targetPort: #{CONTAINER_PORT}#
  selector:
    app: #{APP_NAME}#
    tier: #{TIER_NAME}#
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: #{APP_NAME}#
  namespace: #{NAMESPACE}#
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /app/
        backend:
          serviceName: #{SERVICE_NAME}#
          servicePort: #{PORT}#
`

**Comment by asridharan** [comment]
@bkarakashev we just released helm chart `0.4.0-rc1`. Please give it a try. It has the changes in this PR.

**Comment by akshaysngupta** [comment]
```
helm install -f <helm-config.yaml> application-gateway-kubernetes-ingress/ingress-azure --version 0.4.0-rc1
```

**Comment by bkarakashev** [comment]
I don't want to use Helm.
Can you please tell me where I need to specify the custom health prop in my yaml above?

**Comment by akshaysngupta** [comment]
You need to apply the new helm chart in order to consume the `readinessProbe` that you will define in the the deployment object.
We will add a documentation outlining health probes soon.

**Comment by bkarakashev** [comment]
Not necessary I deploy it using `kubectl apply -f`
So I am already using it but please can you just tell me what is the syntax how to define `readinessProbe` in my Deployment? 

Thanks

```
.........
---
# Source: ingress-azure/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{applicationGatewayName}#-ingress-azure
  labels:
    app: ingress-azure
    chart: ingress-azure-0.4.0-rc1
    heritage: Tiller
    release: #{applicationGatewayName}#
  namespace: #{namespace}#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-azure
      release: #{applicationGatewayName}#
  template:
    metadata:
      labels:
        app: ingress-azure
        release: #{applicationGatewayName}#
        aadpodidbinding: #{applicationGatewayName}#-ingress-azure
    spec:
      serviceAccountName: #{applicationGatewayName}#-sa-ingress-azure
      containers:
      - name: ingress-azure
        image: mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.4.0-rc1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: #{applicationGatewayName}#-cm-ingress-azure
...............
```

**Comment by akshaysngupta** [comment]
You can try something like this
```yaml
containers
- name: #{APP_NAME}#
  ...
  ...
  readinessProbe:
      httpGet:
        path: /health
        port: 80
      periodSeconds: 3
      timeout: 1
```

**Comment by bkarakashev** [comment]
This worked:

```
        livenessProbe:
          httpGet:
            path: /health
            port: 80
```

when I try to use `readinessProbe` I got a syntax error about `timeout` not supported.

Do you know if I can set the HTTP Listener to HTTPS?
And can I have more then one HTTP Listener?
I need to have one HTTP for one of the apps and HTTPS for the other app.
Is this possible?

Thanks

**Comment by akshaysngupta** [comment]
Pardon me, timeout is `timeoutSeconds`
Corrected yaml is
```yaml
containers:
- name: #{APP_NAME}#
  ...
  ...
  readinessProbe:
      httpGet:
        path: /health
        port: 80
      periodSeconds: 3
      timeoutSeconds: 1
```

**Comment by bkarakashev** [comment]
Thank you very much for your help @akshaysngupta. It works like a charm :)

**Pull request merged**
