### PR TITLE
Fixed incorrect yaml code formatting in tutorial.md

### PR DESCRIPTION
**Pull request by mrdfuse**

### CODE REVIEW

**Comment by asridharan** [comment]
@mrdfuse what's the problem with YAML formatting here? Just see a few spaces being added to the YAML spec?

**Comment by mrdfuse** [comment]
@asridharan without those spaces the code block didn't format correctly:
image

**Comment by asridharan** [comment]
> @asridharan without those spaces the code block didn't format correctly:
> image

@mrdfuse sorry didn't follow, what didn't format properly? The markdown rendering?

**Comment by mrdfuse** [comment]
? I have included a screenshot of how it looks like now, the entire code is rendered OUTSIDE the code area in one continuous line, instead of formatted content inside the markdown area.

**Comment by asridharan** [comment]
@mrdfuse sorry for the back and forth and but not sure where you are seeing the rendering. On Github it looks fine:
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/tutorial.md

and it also looks fine on github pages:
https://azure.github.io/application-gateway-kubernetes-ingress/docs/tutorial.html

Are you seeing this in a different browser? A bit odd the screen shot you are describing.

**Comment by wesselkranenborg** [comment]
I'm seeing the same as @mrdfuse. This is my screen on the github page.

image

I'm using Chrome.

**Pull request merged**
