### PR TITLE
Select AGW SKU via feature flag

### PR DESCRIPTION
**Pull request by kvendingoldo**
## Checklist
- [x] The title of the PR is clear and informative
- [ ] If applicable, the changes made in the PR have proper test coverage
- [x] Issues addressed by the PR are mentioned in the description followed by `Fixes`.

## Description

As a user I want to select SKU of AGW. For now, all installations are using `Standard_v2` SKU because it is hardcoded.

## Fixes
None

### CODE REVIEW

**Comment by kvendingoldo** [comment]
@akshaysngupta @3quanfeng can you look at that, please?

**Comment by kvendingoldo** [comment]
@akshaysngupta @3quanfeng  guys, can you take a look, please?

**Comment by gd-asharov** [comment]
@kvendingoldo @akshaysngupta @3quanfeng any updates here?

**Comment by akshaysngupta** [comment]
LGTM

Thanks for contributing! I will merge after testing.

**Review by akshaysngupta — APPROVED** [review]
LGTM! Thanks for contributing!

**Pull request merged**
