### PR TITLE
WIP - AzureIngressAllowedTargets CRDs  support instead AzureIngressProhibitedTargets 

### LINKED ISSUE #1029: Support AzureIngressAllowdTargets to handle several agics managing a shared agw
**Is your feature request related to a problem? Please describe.**
I deployed several cluster during the last months and usualy I use agic with shared agw. We found problems because the clusters handles prohibited target but the humans from one team may buy new domain and add to the agw and they must notify to the another teams that a new domain have to be added to the prohibited target list.

**Describe the solution you'd like**
It will be great if the cluster use a method based in allowed target because only the cluster have to know what domains manages and is not necesary that the other cluster know it.

I have some free time and I think that I can add support to allowed targets if this feature is usefull. I am no sure if this feature should replace the prohibited target in the future but I think that both could work together.

What do you feel about this?

### PR DESCRIPTION
**Pull request by JorTurFer**
## Checklist
- [x] The title of the PR is clear and informative
- [ ] If applicable, the changes made in the PR have proper test coverage (Not yet)
- [x] Issues addressed by the PR are mentioned in the description followed by `Fixes`.

## Description
 This PR fixes the problem related with the knowledge that each cluster needs about another clusters when you are using shared agw. This solution consists in use an allowed manager mode, whose change the logic from deny action to allow action.

I am working in this changes now, but I am not a Golang developer, so probably I make  some mistakes related with possible optimizations or good practices. For this reason, I prefer to make the PR in WIP, in order to be available for code reviews or development tips (or help, of course)

## Fixes
#1029

### CODE REVIEW

**Comment by JorTurFer** [comment]
Development update:
At this point, the functionality feels that works fine and the previous tests are fixed.
The next steps is add the new tests to cover the new feature. I am working in this but I never wrote a test in golang and I am learning about them, just debug a test is a fight (xD). When I finish the new test suite, I will refactor the code trying to make it clearer.
After of those, I will update the docs and the feature will be done.

At this point, any help or suggestion is welcomed.

**Comment by sapher** [comment]
I really need this feature for a client. How can I help ?

**Comment by JorTurFer** [comment]
Hi @sapher 

> I really need this feature for a client. How can I help ?

I am working in the tests but I am not golang developer. I have several problems and I cant debug them. I probed de functionality and it feels good, but I need to write the tests and the related documentation. Do you have any information about how debug tests with ginkgo/gomega? I couldn't find any related with it and that slows me hard :(

**Comment by akshaysngupta** [comment]
@JorTurFer Thanks so much for this PR. I will review this soon.

**Comment by sapher** [comment]
@JorTurFer I'm going to take a look at it. AllowTargets is way more useful than ProhibitedTargets

**Comment by sbkg0002** [comment]
Thank you so much @akshaysngupta !

**Comment by mvrck0** [comment]
@akshaysngupta Any update on this? It would be much appreciated to get this implemented 😄

**Comment by rbickel** [comment]
Any update on this PR ? Waiting for this feature to justify the price of Application Gateway

**Comment by sbkg0002** [comment]
That's rude

**Comment by rbickel** [comment]
@JorTurFer Any reason to close this PR ? Do you want to hand it over ?

**Comment by JorTurFer** [comment]
Hi @rbickel ,
I don't have time to finish it :( You can continue with it where I ended from if you want
I didn't delete the branch in my fork to be able to continue with it :)

**Pull request closed without merging**
